server:
  port: 5000


eureka:
  client:
    serviceUrl:
      default: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#        - id: market-data-service
#          uri: lb://market-data-service
#          predicates:
#            - Path=/market/**
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#          filters:
#            - TokenRelay=
#            - RemoveRequestHeader=Cookie
